### ISSUE TITLE
onBrowserStart not triggered => Error with karma@~0.10

### ISSUE THREAD

**Issue by ath0mas** [matthias-schuetz/karma-htmlfile-reporter#12]
"Suites" is never filled based on browsers ; ends with errors while getting undefined values with "suites[browser.id]".

Error with karma@~0.10 since karma-htmlfile-reporter 0.1.1 (ok with 0.1.0).

Commit 58255fb844cce0ddfa128439361094d25e810593 introduced use of `this.onBrowserStart = function (browser){` instead of `browsers.forEach(function(browser) {`
but *onBrowserStart* seems to have been introduced in karma@0.11 only
See https://github.com/karma-runner/karma-coverage/issues/30

**Comment by matthias-schuetz** [comment]
Thanks for your attention!
I've added a condition and tested it. Now it works again with Karma 0.10 or higher.

**Comment by ath0mas** [comment]
Great ;)
Please release new version on npmjs :package:
