### ISSUE TITLE
FMFILE: too many open files

### ISSUE THREAD

**Issue by SebastianStehle** [matthias-schuetz/karma-htmlfile-reporter#15]
Hi,
I have an issue, similar to this problem: https://github.com/angular/angular/issues/4525

![untitled](https://cloud.githubusercontent.com/assets/1236435/15355340/59743646-1cf2-11e6-98ec-39a9bee3d738.png)

It might be related to the readFileSync method. I hope you can fix it :)

**Comment by dchitwood3** [comment]
I'm having similar issues.

**Comment by matthias-schuetz** [comment]
I'm sorry for the late answer but I had to reproduce the behavior at first. I could accomplish that finally and I also fixed the issue. So the new version (0.2.3) should work normally. It's also published to npm so you can update via console. Also make sure to have the latest versions of Node and Karma installed to be on the safe side.

**Comment by SebastianStehle** [comment]
Awesome, it works :)

**Comment by dchitwood3** [comment]
I second that. Great work on the quick fix.

**Comment by matthias-schuetz** [comment]
Glad to hear! :)

**Comment by dchitwood3** [comment]
Help! With the update to 0.3.0, I'm seeing the issue again. Was there a bad merge?

**Comment by matthias-schuetz** [comment]
Thanks for the info! Indeed, there went something wrong.
Fixed now with 0.3.1, already published to npm!

**Comment by dchitwood3** [comment]
Thanks again. Great tool.
