### ISSUE TITLE
TypeError: Cannot read property 'end' of null

### ISSUE THREAD

**Issue by JHiben** [matthias-schuetz/karma-htmlfile-reporter#17]
I get a _TypeError: Cannot read property 'end' of null_ at the end of all tests (when the report is generated I suppose) and prevents the report to be generated. The error occurs in the index.js file, at 146:44.

I'm running on Windows Server 2008, with Node 4.4.3, npm 2.15.1, karma 0.13.22 (with Jasmine) and karma-htmlfile-reporter 0.3.1. In my karma config I have:
```
reporters: ['progress', 'spec', 'html'],
htmlReporter: {
    outputFile: 'unitTestsResults.html',
    pageTitle: 'A TITLE',
    subPageTitle: 'Unit Tests',
    useLegacyStyle: true
}
```

It's strange because I don't get it directly, but after the second time all tests are checked (when karma is watching).

**Comment by owen-pengtao** [comment]
same issue as mine.
reproduce step:
1. make all the test case to be passed.
2. modify test case, make one test case to be failed, will see that error.
3. modify test case again, make one test case to be failed, the karma can not be running.

Downgrade karma-htmlfile-reporter to version 0.2.3, will fix it.

**Comment by matthias-schuetz** [comment]
Thanks for your attention!
I figured out the problem and fixed it. It occured only when the watching of Karma was enabled. Version 0.2.3 would fix it but only if you use one browser. For multiple browsers it didn't work.
So with the new release 0.3.2, everything works fine. Now I've tested all variants, including multiple browsers with and without watching enabled. It's on npm already.
