### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by SebastianStehle** [matthias-schuetz/karma-htmlfile-reporter#19]
Hi,

I have two feature requests:

1. Make everything a little bit smaller, I don't want to read the report on my smartphone. The font size is too large and there are too much paddings. On my notebook I can only 11 to 12 tests without scrolling. 

2. Group by description prefix

**Comment by matthias-schuetz** [comment]
OK, I've added your features to the newest version (already on npm). For a more compact HTML output, there's a new option called *useCompactStyle*. And suites (*describe* blocks) can be grouped together by setting the option *groupSuites* to *true*. You can see an example output of both options [on this page](http://matthias-schuetz.github.io/karma-htmlfile-reporter/units_groups.html).

**Comment by SebastianStehle** [comment]
Super, das ging aber schnell :)
