### ISSUE TITLE
TypeError: Cannot set property '30465142' of null

### ISSUE THREAD

**Issue by excelulous** [matthias-schuetz/karma-htmlfile-reporter#20]
I get `TypeError: Cannot set property '30465142' of null` after all tests have run.

I'm running on OSX 10.11.16, Node 6.8.1, npm 3.10.8, Karma 1.3.0, karma-htmlfile-reporter 0.2.3.
Here's my Karma config:
```
reporters: ['progress', 'html'],

    // HtmlReporter configuration
    htmlReporter: {
      // Open this file to see results in browser
      outputFile: '_test-output/tests.html',

      // Optional
      pageTitle: 'Unit Tests',
      subPageTitle: __dirname
    }
```

This occurs whenever I run `npm test` in my project.

**Comment by matthias-schuetz** [comment]
Hey, sorry for the late response, I couldn't think of a solution yet.
So I'm glad you figured it out - thanks for the commit!
