### ISSUE TITLE
Cannot set property '####' of undefined (onRunStart not called)

### ISSUE THREAD

**Issue by MikeMatusz** [matthias-schuetz/karma-htmlfile-reporter#28]
It appears with the latest versions of karma-[everything] onRunStart is not always being called (specifically testing using karma-chrome-launcher), and then createHtmlResults is throwing an error because suites is undefined. 

My installed versions of everything unit test related:
"istanbul-instrumenter-loader": "3.0.0",
"jasmine-core": "3.2.1",
"karma": "3.0.0",
"karma-chrome-launcher": "2.2.0",
"karma-coverage": "1.1.2",
"karma-firefox-launcher": "1.1.0",
"karma-htmlfile-reporter": "0.3.6",
"karma-ie-launcher": "1.0.0",
"karma-jasmine": "1.1.2",
"karma-jasmine-html-reporter": "1.3.1",
"karma-spec-reporter": "0.0.32",
"karma-webpack": "3.0.0",
"webpack-karma-die-hard": "1.0.4",

Potentially relevant portions of my karma.conf.js:
frameworks: ['jasmine'],
preprocessors: { 'karma-test-shim.js': ['webpack', 'sourcemap'] },
reporters: ['spec', 'kjhtml', 'html', 'coverage'],
htmlReporter: {
    outputFile: 'tests/results.html',
    pageTitle: 'Features Unit Tests',
    groupSuites: true,
    useCompactStyle: true
},

I will be submitting a PR shortly with a potential solution.  Similar PR's have semi-recently been merged into other reporters such as karma-junit-reporter.  This might be the same issues as #26 but I can't be 100% sure, so it might be worth following up on that after this is addressed.

**Comment by MikeMatusz** [comment]
@matthias-schuetz  Is there any chance you could push a new release to npm?  I have to disable this reporter for one of my projects until this fix is released.

**Comment by matthias-schuetz** [comment]
Sorry, I was in a hurry and didn't publish to npm.
I've updated the version to 0.3.7 and now it's also on npm!
