### ISSUE TITLE
Problem in Config file

### ISSUE THREAD

**Issue by arturokunder** [matthias-schuetz/karma-htmlfile-reporter#8]
Hi

I'm using this versions of karma, jasmine etc:

````
"grunt-karma": "^0.8.3",
"karma-phantomjs-launcher": "^0.1.4",
"karma": "^0.12.16",
"karma-htmlfile-reporter": "^0.1.2"
"karma-jasmine": "^0.1.5",
````

And i'm getting the following error: 

````
Running "karma:unit" (karma) task
Warning: No provider for "framework:jasmine"! (Resolving: framework:jasmine) Use --force to continue.
````

I was able to fix it using this config:

````
reporters: ['progress', 'html'],

htmlReporter: {
      outputFile: 'tests/units.html'
}
````

(Note that i'm not using the plugins line published in the readme)

I'm publishing this here in case anyone has the same problem

Thanks for the plugin!

**Comment by dellinger** [comment]
Confirmed issue is still present.

**Comment by matthias-schuetz** [comment]
OK, I could reproduce it and the "plugins" part has been removed completely from the README.md.
It seems it has gone obsolete so now it works. The plugins part must be left out.
